# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20201117.0.0"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "share/", "/mnt/host"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-focal64-20201117.0.0"
    vb.gui = false
    vb.cpus = 2 # > 2 cores
    vb.memory = 4096 # > 4GB
  end

  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provision "shell", inline: <<-SHELL
    apt install -y net-tools
    wget https://releases.jfrog.io/artifactory/artifactory-debs/pool/jfrog-artifactory-cpp-ce/jfrog-artifactory-cpp-ce-7.25.5.deb
    dpkg -i jfrog-artifactory-cpp-ce-7.25.5.deb
    service artifactory status
    service artifactory start
    service artifactory status
  SHELL

end
